from django.contrib import admin
from django.utils.html import format_html

from .models import Video

# Register your models here.

# The @admin.register() decorator performs the same function as
# admin.site.register(Video, VideoAdmin). It registers the ModelAdmin class.


@admin.register(Video)
class VideoAdmin(admin.ModelAdmin):
    """
    Customizes the admin interface for the Video model.
    """
    # Defines the columns displayed in the change list view of the admin.
    list_display = (
        'title',
        'category',
        'created_at',
        'video_file',
        'thumbnail_preview'
    )
    
    # Specifies fields that should be displayed as read-only.
    # 'thumbnail_preview' is generated by a method, so it must be read-only.
    readonly_fields = ('thumbnail_preview',)
    
    # Adds a sidebar to filter the change list by the 'category' field.
    list_filter = ('category',)

    # Enables a search box at the top of the change list, searching the
    # specified fields.
    search_fields = ('title', 'description')
    
    # Organizes the fields on the add/change page into logical groups (fieldsets).
    fieldsets = (
        (None, {
            'fields': ('title', 'description', 'category', 'video_file')
        }),
        # The second group is for the automatically generated preview.
        ('Vorschaubild (automatisch generiert)', {
            'fields': ('thumbnail_preview',),
        }),
    )

    readonly_fields = ('thumbnail_preview',)

    def thumbnail_preview(self, obj):
        """
        Creates an HTML img tag to display the thumbnail in the admin.

        This method is used for both the 'list_display' and the 'readonly_fields'.
        It checks if a thumbnail exists and has a URL.

        Args:
            obj: The Video instance.

        Returns:
            str: An HTML string for the image tag or a default message.
        """
        # Check if the thumbnail_url field is not empty and has a URL attribute.
        if obj.thumbnail_url and hasattr(obj.thumbnail_url, 'url'):
            # Use format_html to safely render HTML. It prevents auto-escaping.
            # This creates a clickable image preview.
            return format_html(
                '<a href="{0}" target="_blank">'
                '<img src="{0}" style="max-height: 50px;" />'
                '</a>',
                obj.thumbnail_url.url
            )
        # Display a message if no thumbnail is available yet.
        return "Wird nach dem Speichern generiert..."

    # Sets the column header text for the 'thumbnail_preview' method in the admin.
    thumbnail_preview.short_description = 'Vorschau'
